name: Сборка Luna Messenger

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Собрать APK
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Установить Android SDK
        uses: android-actions/setup-android@v3

      - name: Собрать APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Сохранить APK
        uses: actions/upload-artifact@v4
        with:
          name: Luna-Messenger-APK
          path: app/build/outputs/apk/debug/app-debug.apk
